### ISSUE TITLE
[Discussion] Decide on a name

### ISSUE THREAD

**Issue by kgizdov** [kgizdov/arch-installer#1]
We need a name for this project. Work-in-progress name is Arch Installer. If you have a better name, put it in the comments with a small reason why it would be better and why it suits the project.

**Comment by shibumi** [comment]
I think we should just name it 'arch installer'. If we come up with a fancy name we can still put that sticker later on it.

**Comment by kgizdov** [comment]
I think we should have that issue open and if people come up at some point with a good idea, they'll put it here and I'll update the options and so on.

**Comment by shibumi** [comment]
Can we close the polls? They are public and somehow they look broken. lol

**Comment by kgizdov** [comment]
@shibumi done

**Comment by kgizdov** [comment]
My favourite so far is **ISOF**

**Comment by kgizdov** [comment]
this project will be archived until further notice
