### ISSUE TITLE
[Discussion] Decide on a framework/language to use

### ISSUE THREAD

**Issue by kgizdov** [kgizdov/arch-installer#2]
We want to provide a TUI and a GUI. TUI at first and then with time a GUI (or the opposite or a mixed thing). Let's discuss what would be an appropriate way of doing that. For requirements, please refer to #3 until they are finalised.

**Comment by shibumi** [comment]
Can we close the polls? They are public and somehow they look broken. lol

**Comment by kgizdov** [comment]
@shibumi done

**Comment by kgizdov** [comment]
this project will be archived until further notice
