### ISSUE TITLE
[Discussion] Let's collect some requirements

### ISSUE THREAD

**Issue by shibumi** [kgizdov/arch-installer#3]
Let's collect some requirements for our installer. First we have the following three options:

* Ncurses
* Interactive CLI
* Just a bash script with parameters
* A graphical installer

As far as we know, we had an interactive CLI installer, an ncurses installer and bash scripts already. 

Also: Which problem do we want to solve with this installer? And which people do we want to address with it?

I think the following:
Arch Linux provides already a simple way to install it via using commands in the shell. So most "Shell-Junkies" should be satisfied and I expect that these "Shell-Junkies" have enough knowledge to create an install script for their favourite Arch Linux installation by themselves.

Therefore, I conclude, we should try something new and use a graphical installer.
If so then we would have the following options:

* We can write a new one from scratch (HAHA.. no)
* [Calamares](https://github.com/calamares/calamares)
* [Anaconda](https://github.com/rhinstaller/anaconda)
* [Chnchi](https://github.com/Antergos/Cnchi)
* Any addition?

So, maybe we should start the whole project, with collecting information about different graphical installer frameworks.

**Comment by kgizdov** [comment]
My original idea was a bit different. At first we should provide a TUI of some sort, where Arch people are more comfortable. Then we add a GUI as time goes on. But all the while this following is preserved:
 - start a prompt of some kind and as the user what they want
 - full manual
 - TUI with very advanced differentiated options
 - GUI for beginners and less advanced, more streamlined install

I also think it's important at each step of config (per OS component such as I/O, network, etc.) to provide the user to pop out and do a manual config of some sort and then pop back in. That I think will be the hardest to achieve, but could probably make sure we test for working config after each step. And I'm sure that would already be part of the process.

**Comment by shibumi** [comment]
Well, the problem is, that you can't stick a GUI over a TUI. You would need to create both from scratch, but if we want to use a finished GUI installer framework, we can't create a TUI for it. The TUI will be 100% separate of the GUI installer. Furthermore, I really think that a TUI is pointless, because I expect that most of our users can write bash scripts for installing arch linux by themselves. 

So my question for you is:

**Who do you want to address with this installer? Linux Newbies? Linux Experts? And which problem do you want to solve with it?**

I don't say we shouldn't provide both a TUI and GUI, but I think we should see them as two totally different projects. They have nothing to do to each other. In my understanding we will provide 2 ISOs, one for cli installation and one for graphical installation.

**Comment by Foxboron** [comment]
>My original idea was a bit different. At first we should provide a TUI of some sort, where Arch people are more comfortable. Then we add a GUI as time goes on. But all the while this following is preserved

The installer will not replace `arch-install-scripts` or the current installation process. It is only going to be one alternative.

**Comment by kgizdov** [comment]
@shibumi I understand this would make us create a TUI and a GUI, but I don't want to go the road of having a TUI for a GUI - that would be a nightmare. I would like to have the option to ship them both and let the user decide what they wanna do - start one or the other.
I wanna solve the problem of not having to run all the initial steps manually at boot time: verify efivars (omg - do it for me!), create my own partitions (give me options to choose from!), format stuff(options?!), networks (what year is this?), update the system clock (FOR REAL???)....
 
@Foxboron the installer is most likely gonna use arch-install-scripts

**Comment by kgizdov** [comment]
In summary:
 - use arch-install-scripts for final or pre-final step (if user wants to install/change stuff later)
 - automate as much as possible (but still ask - would need to find a delicate balance here)
 - give TUI && GUI options in final product (TUI of whatever sort would do initially, of course)

**Comment by coderobe** [comment]
>Well, the problem is, that you can't stick a GUI over a TUI

You totally can. Write a library that handles all the installer features, and have the frontends load and use that. This way, you're not duplicating logic and can implement the frontend however many times you like.

**Comment by coderobe** [comment]
Additionally, GUI comes with massive size gain due to the requirement of shipping X with all its drivers and libraries, and your GUI framework library - i.e. QT
This will never go past releng.

I recommend sticking to a TUI as that can be implemented in a few MiB and does not inflate the ISO size for no solid reason other than to provide a mouse cursor.

**Comment by coderobe** [comment]
>If so then we would have the following options:
>
>We can write a new one from scratch (HAHA.. no)
>Calamares
>Anaconda
>Chnchi

Calamares does not feature sane error handling, which is vital.
Chnchi is dead.

You do not need an "installer framework" to configure a system.

**Comment by kgizdov** [comment]
@coderobe I agree that we should start with a TUI for those reasons and probably it's simpler to implement. However, I do think we should eventually provide both. Maybe you are correct GUI will never pass approval, but maybe we can provide people with instruction on how to make ISOs with it. Then I'm sure users will enjoy it.

**Comment by coderobe** [comment]
Bikeshedding on whether or not it should be a GUI is non-blocking, the backend can (and should) be developed separately from the frontend logic anyways.

**Comment by kgizdov** [comment]
@coderobe I agree. Do you know of anything that exists that would help us not develop a backend from scratch?

**Comment by shibumi** [comment]
> > Well, the problem is, that you can't stick a GUI over a TUI
> 
> You totally can. Write a library that handles all the installer features, and have the frontends load and use that. This way, you're not duplicating logic and can implement the frontend however many times you like.

Sorry, I will be more precise. I mean't "you can't stick a existing GUI framework without modifications over a custom TUI" it will produce too much effort to achieve support for that TUI in the GUI framework.

**Comment by shibumi** [comment]
> @coderobe I agree that we should start with a TUI for those reasons and probably it's simpler to implement. However, I do think we should eventually provide both. Maybe you are correct GUI will never pass approval, but maybe we can provide people with instruction on how to make ISOs with it. Then I'm sure users will enjoy it.

Actually it will not pass approval only if we try to push the GUI installer in the current ISO. As I said, in my vision we have two ISOs and then size shouldn't be a problem. We will have one bloated GUI ISO and one slim ISO for the shell junkies. it's that simple.

I still think working on a TUI is pointless, we want to address new people to arch linux with this project  and I think a graphical installer is the best way to achieve this. A TUI will still fright too much users out there.

**Comment by kgizdov** [comment]
@shibumi I don't think so. If we come up with a decent API we can plug it into anything with little intervention. Also, my main goal is not only to bring new people to Arch. To be totally honest, that is probably a side effect. I just want Arch Linux installations to come and join the 21st century where things that are super standard and can be automated are automated. I want a better smarter installation overall.

**Comment by shibumi** [comment]
@kgizdov Well, that's the point, I don't think that you can plug your TUI so easily into every GUI framework. Do you understand how anaconda or calamares work? They don't have an API to forward such things too. Anaconda uses XML kickup scripts, and these are totally unrelated to a TUI.

That's why I highly suggest, that we first gather some information about GUI installer frameworks and then port this installer to arch and then if everything works fine work on a TUI, because connecting the TUI with the GUI will be much more work as you expect it is.

**Except you want to create a fully new GUI installer framework**

**Comment by shibumi** [comment]
> To be totally honest, that is probably a side effect. I just want Arch Linux installations to come and join the 21st century where things that are super standard and can be automated are automated. I want a better smarter installation overall.

That's why I have asked you, what problem do you want to solve. And it seems like we have totally different targets. You just want to automate the installation process and I want to make the installation process more accessible for users without deep linux knowledge.

Do you understand know, why I asked what we actually want to achieve? and which users groups we want to address with this?

**Comment by kgizdov** [comment]
@shibumi I think you misunderstood who is providing the API. As @coderobe suggested, we write a lib of even a bunch of scripts (or whatever) with a common entry point and an API - then you make your existing frontend (TUI or GUI) framework call your API, by changing a few of the low level worker functions in that framework.

**Comment by shibumi** [comment]
@kgizdov I ask again, do you understand how anaconda or calamares or any other GUI framework works? Are you sure that this is possible with the frameworks? because I am not. I have no idea about how they work, I don't develop them and I never had a deep look inside of them, that's why I said we should gather information about them first and port them and see if it's actually possible to do this

**Comment by kgizdov** [comment]
@shibumi I think you misunderstand. Don't be mad, please. Of course, we will gather info, but however they work, we can make broad assumptions about them - they do not do everything from the ground up. IF calamares is a portable framework, then it should be possible to specify which package manager you use and what files go where and so on on each system. This is where our low level stuff is gonna fit. Those frameworks use low level functions that actually do the work the high-level calls want done - there we fit our API. It's true for any such project.

Also, just because we want an installer for different reasons, doesn't mean it's a bad thing. I think it's actually a good thing. We both want an installer either way and wanting different things makes it such that the installer will end up satisfying more needs in the end. But we will need to discuss a bit more how we go about. I see nothing wrong or worrying about that.

**Comment by sonuishaq67** [comment]
Hey hope this is not necrobumping the thread but why don't you just use gtk with xlibs
As for the TUI you can keep the iso same and make a package for this so we can just install it with pacman and starting the gui with a command like (xstart)
So win-win for TUI and GUI you can do a GUI install if you want or just TUI one

**Comment by Rash419** [comment]
> Hey hope this is not necrobumping the thread but why don't you just use gtk with xlibs
> As for the TUI you can keep the iso same and make a package for this so we can just install it with pacman and starting the gui with a command like (xstart)
> So win-win for TUI and GUI you can do a GUI install if you want or just TUI one

Cool Idea

**Comment by kgizdov** [comment]
@sonuishaq67 no worries, this project is on hold atm. For a similar idea look at [this](https://github.com/Torxed/archinstall)

**Comment by sonuishaq67** [comment]
okays @kgizdov
I came here from the arch linux [gsoc page](https://wiki.archlinux.org/index.php/DeveloperWiki:Google_Summer_of_Code) to see if i can work on this

**Comment by kgizdov** [comment]
@sonuishaq67 glad to see you are interested. You are welcome to work on it. Unfortunately, Arch Linux did not get the sponsorship of GSOC this year, so we could not find all hands needed to develop this project further at present. However, if you have time, an idea and will to work on something, you are most welcome.

**Comment by Rash419** [comment]
> okays @kgizdov
> I came here from the arch linux [gsoc page](https://wiki.archlinux.org/index.php/DeveloperWiki:Google_Summer_of_Code) to see if i can work on this 

Lol I came here after seeing that only

**Comment by sonuishaq67** [comment]
> Arch Linux did not get the sponsorship of GSOC this year 

@kgizdov for 2020 right ? cause [2021 gsoc timeline](https://summerofcode.withgoogle.com/how-it-works/) came out day before yesterday and  :crossed_fingers: I hope to see arch linux for 2021
>  However, if you have time, an idea and will to work on something, you are most welcome.

yep i wanted to see a website for arch linux like fedoras https://whatcanidoforfedora.org theres a repo on the [organisation](https://github.com/archlinux/) [forked](https://github.com/archlinux/asknot-ng) from fedora-infra and i sent a pr for that

**Comment by kgizdov** [comment]
this project will be archived until further notice
